// <auto-generated/>

global using global::CleanArchitecture.Core.Enumerations;
global using global::CleanArchitecture.Core.Models.Errors;
global using global::Microsoft.EntityFrameworkCore;
global using global::Microsoft.EntityFrameworkCore.Metadata.Builders;
global using global::Microsoft.Extensions.DependencyInjection;
global using global::Microsoft.Extensions.Logging;
global using global::System;
global using global::System.Collections.Generic;
global using global::System.Linq;
global using global::System.Linq.Expressions;