// <auto-generated/>
global using global::CleanArchitecture.Core.Enumerations;
global using global::CleanArchitecture.Core.Extensions;
global using global::CleanArchitecture.Core.Models.Errors;
global using global::Microsoft.AspNetCore.Hosting;
global using global::Microsoft.AspNetCore.Http;
global using global::Microsoft.Extensions.DependencyInjection;
global using global::Microsoft.Extensions.Logging;
global using global::System;
global using global::System.Collections.Generic;
global using global::System.Globalization;
global using global::System.Linq;
global using global::System.Linq.Expressions;
global using global::System.Security.Claims;
